hadolint:
  name: "Hadolint scan"
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3


    - name: Run hadolint
      uses: hadolint/hadolint-action@v2.1.0
      with:
        dockerfile: ./Dockerfile
        format: sarif
        output-file: hadolint-results.sarif

    - name: Upload analysis results to GitHub
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: hadolint-results.sarif
        wait-for-processing: true

